### ISSUE TITLE
Possible modification to the slide-left menu

### ISSUE THREAD

**Issue by tarang9211** [callmenick/Slide-Push-Menus#3]
Hi Nick. 

Is there a way I could implement this without any javascript? I'm avoiding the use of jQuery and Prototype. If so, let me know. I'd love to use this menu and give credit where it's due if i could keep this simple (CSS only)

**Comment by callmenick** [comment]
@tarang9211 You could look into checkboxes, the `:checked` pseudo class, and sibling selectors to achieve something similar with only CSS.
